import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

export const PRESET_HANDBOOK = 'handbook'
export const PRESET_CONVENTIONAL = 'conventional'

export const CONVENTIONAL_TYPES = [
  'feat', 'fix', 'docs', 'style', 'refactor',
  'perf', 'test', 'build', 'ci', 'chore', 'revert',
]

const HANDBOOK_VERBS = ['Add', 'Fix', 'Remove', 'Update', 'Refactor', 'Test']

/**
 * Read preset from .house-rules.json at repoRoot.
 * Returns 'handbook' if missing or unreadable.
 * @param {string | null | undefined} repoRoot
 * @returns {'handbook' | 'conventional'}
 */
export function readConfigPreset(repoRoot) {
  if (!repoRoot) return PRESET_HANDBOOK
  const configPath = join(repoRoot, '.house-rules.json')
  if (!existsSync(configPath)) return PRESET_HANDBOOK
  try {
    const raw = readFileSync(configPath, 'utf8')
    const config = JSON.parse(raw)
    const preset = config?.['commit-message']?.preset
    if (preset === PRESET_CONVENTIONAL) return PRESET_CONVENTIONAL
    return PRESET_HANDBOOK
  } catch {
    return PRESET_HANDBOOK
  }
}

/**
 * Lint a commit message.
 * @param {string} message
 * @param {{ preset?: string, repoRoot?: string | null }} [opts]
 * @returns {{ violations: Array<{line: number, group: string, reason: string}>, preset: string }}
 */
export function lintCommitMessage(message, opts = {}) {
  const preset =
    opts.preset ??
    readConfigPreset(opts.repoRoot) ??
    PRESET_HANDBOOK

  const lines = message.split('\n')
  const subject = lines[0] ?? ''
  const violations = []

  // Skip subject checks for auto-generated commits
  const isAutoGenerated = /^(fixup|squash)! /.test(subject)

  if (!isAutoGenerated) {
    if (preset === PRESET_HANDBOOK) {
      const startsWithVerb = HANDBOOK_VERBS.some(v => subject.startsWith(v))
      if (!startsWithVerb) {
        violations.push({
          line: 1,
          group: 'subject',
          reason: `Subject must start with one of: ${HANDBOOK_VERBS.join(', ')}`,
        })
      }
      if (subject.length > 50) {
        violations.push({
          line: 1,
          group: 'subject',
          reason: `Subject must be ≤50 characters (got ${subject.length})`,
        })
      }
    } else if (preset === PRESET_CONVENTIONAL) {
      const CONVENTIONAL_RE = /^([a-zA-Z0-9_-]+)(?:\([^)]*\))?!?:\s+\S/
      if (!CONVENTIONAL_RE.test(subject)) {
        violations.push({
          line: 1,
          group: 'subject',
          reason: 'Subject must match type(scope)?: description format',
        })
      } else {
        const typeMatch = subject.match(/^([a-zA-Z0-9_-]+)/)
        if (typeMatch && !CONVENTIONAL_TYPES.includes(typeMatch[1])) {
          violations.push({
            line: 1,
            group: 'subject',
            reason: `Unknown type "${typeMatch[1]}"; allowed: ${CONVENTIONAL_TYPES.join(', ')}`,
          })
        }
      }
      if (subject.length > 72) {
        violations.push({
          line: 1,
          group: 'subject',
          reason: `Subject must be ≤72 characters (got ${subject.length})`,
        })
      }

      // Conventional: no body allowed
      if (lines.length > 1) {
        const blankLine = lines[1]
        if (blankLine !== '') {
          violations.push({
            line: 2,
            group: 'body',
            reason: 'Line 2 must be blank when body is present',
          })
        }
        const bodyLines = lines.slice(2)
        const nonBlankBodyLines = bodyLines.filter(l => l.trim() !== '')
        if (nonBlankBodyLines.length > 0) {
          violations.push({
            line: 3,
            group: 'body',
            reason: 'Conventional commits must not have a body',
          })
        }
      }
    }
  }

  return { violations, preset }
}
