// test/motive-tickets.test.ts
// Tests for hooks/lib/motive-tickets.mjs — T4 acceptance criteria.
//
// T4-AC1  A hand-authored tickets/ file survives regenerateMotiveTickets byte-identical.
// T4-AC2  Per-slice ticket generation is absent — no files written to tickets/ for slices.
// T4-AC3  Open-item drill-downs are written to open-items/, not tickets/.
// T4-AC4  Sweep is scoped to open-items/ only — stale open-items removed, tickets/ untouched.
// T4-AC5  Module never throws — bad input degrades gracefully.

import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import {
  mkdirSync,
  writeFileSync,
  readFileSync,
  rmSync,
  existsSync,
  readdirSync,
} from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { regenerateMotiveTickets, sanitizeId, migrateAutoGeneratedTickets } from '../hooks/lib/motive-tickets.mjs'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeTmp() {
  const dir = join(tmpdir(), `gw-mt-test-${Date.now()}-${Math.random().toString(36).slice(2)}`)
  mkdirSync(dir, { recursive: true })
  return dir
}

// ---------------------------------------------------------------------------
// sanitizeId (basic contract — unchanged from pre-T4)
// ---------------------------------------------------------------------------

describe('sanitizeId', () => {
  it('lowercases and replaces unsafe chars with hyphens', () => {
    expect(sanitizeId('TBD-1')).toBe('tbd-1')
    expect(sanitizeId('S-ANCHOR')).toBe('s-anchor')
  })

  it('returns null for path-traversal attempts', () => {
    expect(sanitizeId('../evil')).toBeNull()
    expect(sanitizeId('foo/bar')).toBeNull()
  })

  it('returns null for empty / non-string input', () => {
    expect(sanitizeId('')).toBeNull()
    expect(sanitizeId(null as any)).toBeNull()
    expect(sanitizeId(42 as any)).toBeNull()
  })
})

// ---------------------------------------------------------------------------
// T4-AC1  hand-authored tickets/ file survives byte-identical
// ---------------------------------------------------------------------------

describe('T4-AC1 — tickets/ is never written or deleted', () => {
  let motiveDir: string

  beforeEach(() => { motiveDir = makeTmp() })
  afterEach(() => { rmSync(motiveDir, { recursive: true, force: true }) })

  it('leaves a hand-authored ticket file byte-identical after regeneration', () => {
    const ticketsDir = join(motiveDir, 'tickets')
    mkdirSync(ticketsDir, { recursive: true })
    const ticketPath = join(ticketsDir, 'foo.md')
    const original = '# My hand-authored ticket\n\nPrecious content.\n'
    writeFileSync(ticketPath, original, 'utf8')

    regenerateMotiveTickets(motiveDir, {
      slices: [{ id: 'foo', desc: 'Slice foo', status: 'ready' }],
      openItems: [],
      events: [],
    })

    expect(readFileSync(ticketPath, 'utf8')).toBe(original)
  })

  it('does not create tickets/ when it did not exist', () => {
    regenerateMotiveTickets(motiveDir, {
      slices: [{ id: 'S-1', desc: 'A slice', status: 'ready' }],
      openItems: [],
      events: [],
    })

    expect(existsSync(join(motiveDir, 'tickets'))).toBe(false)
  })

  it('does not add any files to an existing tickets/ dir', () => {
    const ticketsDir = join(motiveDir, 'tickets')
    mkdirSync(ticketsDir, { recursive: true })
    // pre-existing human file
    writeFileSync(join(ticketsDir, 'existing.md'), '# Existing\n', 'utf8')

    regenerateMotiveTickets(motiveDir, {
      slices: [{ id: 'existing', desc: 'Same id', status: 'complete' }],
      openItems: [],
      events: [],
    })

    const files = readdirSync(ticketsDir)
    expect(files).toEqual(['existing.md'])
    expect(readFileSync(join(ticketsDir, 'existing.md'), 'utf8')).toBe('# Existing\n')
  })
})

// ---------------------------------------------------------------------------
// T4-AC2  per-slice ticket generation is absent
// ---------------------------------------------------------------------------

describe('T4-AC2 — slices do not produce any generated files', () => {
  let motiveDir: string

  beforeEach(() => { motiveDir = makeTmp() })
  afterEach(() => { rmSync(motiveDir, { recursive: true, force: true }) })

  it('produces nothing in tickets/ even with many slices', () => {
    regenerateMotiveTickets(motiveDir, {
      slices: [
        { id: 'S-1', desc: 'Slice 1', status: 'ready' },
        { id: 'S-2', desc: 'Slice 2', status: 'complete' },
        { id: 'S-3', desc: 'Slice 3', status: 'in_progress' },
      ],
      openItems: [],
      events: [],
    })

    expect(existsSync(join(motiveDir, 'tickets'))).toBe(false)
  })
})

// ---------------------------------------------------------------------------
// T4-AC3  open-item drill-downs written to open-items/
// ---------------------------------------------------------------------------

describe('T4-AC3 — open-item drill-downs go to open-items/', () => {
  let motiveDir: string

  beforeEach(() => { motiveDir = makeTmp() })
  afterEach(() => { rmSync(motiveDir, { recursive: true, force: true }) })

  it('creates open-items/ and writes a file per open item', () => {
    regenerateMotiveTickets(motiveDir, {
      slices: [],
      openItems: [
        { id: 'TBD-1', statement: 'Which approach?', kind: 'TBD' },
        { id: 'TBD-2', statement: 'Which format?', kind: 'TBD' },
      ],
      events: [],
    })

    const openItemsDir = join(motiveDir, 'open-items')
    expect(existsSync(openItemsDir)).toBe(true)
    expect(existsSync(join(openItemsDir, 'tbd-1.md'))).toBe(true)
    expect(existsSync(join(openItemsDir, 'tbd-2.md'))).toBe(true)
  })

  it('generated open-item file contains id and statement', () => {
    regenerateMotiveTickets(motiveDir, {
      slices: [],
      openItems: [{ id: 'TBD-3', statement: 'Pick a color', kind: 'TBD' }],
      events: [],
    })

    const content = readFileSync(join(motiveDir, 'open-items', 'tbd-3.md'), 'utf8')
    expect(content).toContain('TBD-3')
    expect(content).toContain('Pick a color')
  })

  it('does NOT write open-item files to tickets/', () => {
    regenerateMotiveTickets(motiveDir, {
      slices: [],
      openItems: [{ id: 'TBD-1', statement: 'Which approach?', kind: 'TBD' }],
      events: [],
    })

    expect(existsSync(join(motiveDir, 'tickets'))).toBe(false)
  })

  it('includes related DECISION events in the drill-down', () => {
    regenerateMotiveTickets(motiveDir, {
      slices: [],
      openItems: [{ id: 'TBD-1', statement: 'Pick approach', kind: 'TBD' }],
      events: [
        { type: 'DECISION', msg: 'We pick approach A for TBD-1', ts: '2026-01-01T00:00:00Z', data: {} },
        { type: 'DECISION', msg: 'Unrelated decision', ts: '2026-01-02T00:00:00Z', data: {} },
      ],
    })

    const content = readFileSync(join(motiveDir, 'open-items', 'tbd-1.md'), 'utf8')
    expect(content).toContain('approach A')
    expect(content).not.toContain('Unrelated decision')
  })
})

// ---------------------------------------------------------------------------
// T4-AC4  sweep scoped to open-items/ only
// ---------------------------------------------------------------------------

describe('T4-AC4 — stale sweep hits open-items/ only', () => {
  let motiveDir: string

  beforeEach(() => { motiveDir = makeTmp() })
  afterEach(() => { rmSync(motiveDir, { recursive: true, force: true }) })

  it('removes stale open-items/ files when open item disappears from charter', () => {
    // First pass: two open items
    regenerateMotiveTickets(motiveDir, {
      slices: [],
      openItems: [
        { id: 'TBD-1', statement: 'Old item', kind: 'TBD' },
        { id: 'TBD-2', statement: 'Keeper', kind: 'TBD' },
      ],
      events: [],
    })

    // Second pass: TBD-1 removed
    regenerateMotiveTickets(motiveDir, {
      slices: [],
      openItems: [{ id: 'TBD-2', statement: 'Keeper', kind: 'TBD' }],
      events: [],
    })

    const openItemsDir = join(motiveDir, 'open-items')
    expect(existsSync(join(openItemsDir, 'tbd-1.md'))).toBe(false)
    expect(existsSync(join(openItemsDir, 'tbd-2.md'))).toBe(true)
  })

  it('does NOT remove hand-authored tickets/ files even when matching ids disappear', () => {
    // Create a hand-authored ticket with same id as an open item
    const ticketsDir = join(motiveDir, 'tickets')
    mkdirSync(ticketsDir, { recursive: true })
    const handWritten = '# TBD-1 ticket\n\nHand authored.\n'
    writeFileSync(join(ticketsDir, 'tbd-1.md'), handWritten, 'utf8')

    // Run with no open items — would sweep if tickets/ were in scope
    regenerateMotiveTickets(motiveDir, {
      slices: [],
      openItems: [],
      events: [],
    })

    expect(readFileSync(join(ticketsDir, 'tbd-1.md'), 'utf8')).toBe(handWritten)
  })
})

// ---------------------------------------------------------------------------
// T4-AC5  never throws on bad input
// ---------------------------------------------------------------------------

describe('T4-AC5 — never throws on bad input', () => {
  let motiveDir: string

  beforeEach(() => { motiveDir = makeTmp() })
  afterEach(() => { rmSync(motiveDir, { recursive: true, force: true }) })

  it('handles null/undefined slices and openItems gracefully', () => {
    expect(() =>
      regenerateMotiveTickets(motiveDir, {} as any),
    ).not.toThrow()
  })

  it('handles open items with missing / null ids', () => {
    expect(() =>
      regenerateMotiveTickets(motiveDir, {
        slices: [],
        openItems: [{ id: null as any, statement: 'No id' }, { id: '../evil', statement: 'Bad id' }],
        events: [],
      }),
    ).not.toThrow()
  })

  it('handles a non-existent motiveDir by creating open-items/', () => {
    rmSync(motiveDir, { recursive: true, force: true })
    expect(() =>
      regenerateMotiveTickets(motiveDir, {
        slices: [],
        openItems: [{ id: 'TBD-1', statement: 'Test', kind: 'TBD' }],
        events: [],
      }),
    ).not.toThrow()

    expect(existsSync(join(motiveDir, 'open-items', 'tbd-1.md'))).toBe(true)
  })
})

// ---------------------------------------------------------------------------
// F16 — migrateAutoGeneratedTickets: anchored footer match
// ---------------------------------------------------------------------------

const AUTOGEN_FOOTER = '_Auto-generated — do not edit by hand._'

describe('migrateAutoGeneratedTickets — F16 footer anchor', () => {
  let motiveDir: string
  let ticketsDir: string

  beforeEach(() => {
    motiveDir = makeTmp()
    ticketsDir = join(motiveDir, 'tickets')
    mkdirSync(ticketsDir, { recursive: true })
  })

  afterEach(() => { rmSync(motiveDir, { recursive: true, force: true }) })

  it('deletes a genuine autogen file (footer is last non-empty line)', () => {
    const autogenContent = `# Auto ticket\n\nSome body text.\n\n${AUTOGEN_FOOTER}\n`
    writeFileSync(join(ticketsDir, 'autogen.md'), autogenContent, 'utf8')

    const deleted = migrateAutoGeneratedTickets(motiveDir)

    expect(deleted).toHaveLength(1)
    expect(deleted[0]).toContain('autogen.md')
    expect(existsSync(join(ticketsDir, 'autogen.md'))).toBe(false)
  })

  it('survives a hand-edited ticket that QUOTES the footer mid-document', () => {
    // Footer appears in prose — should NOT be deleted
    const handEdited = `# t8\n\n## Notes\n\nWe removed the old \`${AUTOGEN_FOOTER}\` marker.\n\n## Status\n\nIn progress.\n`
    writeFileSync(join(ticketsDir, 't8.md'), handEdited, 'utf8')

    const deleted = migrateAutoGeneratedTickets(motiveDir)

    expect(deleted).toHaveLength(0)
    expect(existsSync(join(ticketsDir, 't8.md'))).toBe(true)
    expect(readFileSync(join(ticketsDir, 't8.md'), 'utf8')).toBe(handEdited)
  })

  it('returns empty array when tickets/ does not exist', () => {
    rmSync(ticketsDir, { recursive: true, force: true })
    const deleted = migrateAutoGeneratedTickets(motiveDir)
    expect(deleted).toEqual([])
  })

  it('returns empty array when no autogen files present', () => {
    writeFileSync(join(ticketsDir, 'hand.md'), '# hand\n\nNo footer.\n', 'utf8')
    const deleted = migrateAutoGeneratedTickets(motiveDir)
    expect(deleted).toEqual([])
  })

  it('handles footer with trailing whitespace on last line', () => {
    const content = `# ticket\n\nbody\n\n${AUTOGEN_FOOTER}   \n`
    writeFileSync(join(ticketsDir, 'trailing.md'), content, 'utf8')
    const deleted = migrateAutoGeneratedTickets(motiveDir)
    expect(deleted).toHaveLength(1)
  })
})
