import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import {
  mkdirSync,
  writeFileSync,
  readFileSync,
  rmSync,
  existsSync,
} from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { sanitizeId, migrateAutoGeneratedTickets } from '../hooks/lib/motive-tickets.mjs'

function makeTmp() {
  const dir = join(tmpdir(), `gw-mt-test-${Date.now()}-${Math.random().toString(36).slice(2)}`)
  mkdirSync(dir, { recursive: true })
  return dir
}

describe('sanitizeId', () => {
  it('lowercases and replaces unsafe chars with hyphens', () => {
    expect(sanitizeId('TBD-1')).toBe('tbd-1')
    expect(sanitizeId('S-ANCHOR')).toBe('s-anchor')
  })

  it('returns null for path-traversal attempts', () => {
    expect(sanitizeId('../evil')).toBeNull()
    expect(sanitizeId('foo/bar')).toBeNull()
  })

  it('returns null for empty / non-string input', () => {
    expect(sanitizeId('')).toBeNull()
    expect(sanitizeId(null as any)).toBeNull()
    expect(sanitizeId(42 as any)).toBeNull()
  })
})

const AUTOGEN_FOOTER = '_Auto-generated — do not edit by hand._'

describe('migrateAutoGeneratedTickets — F16 footer anchor', () => {
  let motiveDir: string
  let ticketsDir: string

  beforeEach(() => {
    motiveDir = makeTmp()
    ticketsDir = join(motiveDir, 'tickets')
    mkdirSync(ticketsDir, { recursive: true })
  })

  afterEach(() => { rmSync(motiveDir, { recursive: true, force: true }) })

  it('deletes a genuine autogen file (footer is last non-empty line)', () => {
    const autogenContent = `# Auto ticket\n\nSome body text.\n\n${AUTOGEN_FOOTER}\n`
    writeFileSync(join(ticketsDir, 'autogen.md'), autogenContent, 'utf8')

    const deleted = migrateAutoGeneratedTickets(motiveDir)

    expect(deleted).toHaveLength(1)
    expect(deleted[0]).toContain('autogen.md')
    expect(existsSync(join(ticketsDir, 'autogen.md'))).toBe(false)
  })

  it('survives a hand-edited ticket that QUOTES the footer mid-document', () => {
    const handEdited = `# t8\n\n## Notes\n\nWe removed the old \`${AUTOGEN_FOOTER}\` marker.\n\n## Status\n\nIn progress.\n`
    writeFileSync(join(ticketsDir, 't8.md'), handEdited, 'utf8')

    const deleted = migrateAutoGeneratedTickets(motiveDir)

    expect(deleted).toHaveLength(0)
    expect(existsSync(join(ticketsDir, 't8.md'))).toBe(true)
    expect(readFileSync(join(ticketsDir, 't8.md'), 'utf8')).toBe(handEdited)
  })

  it('returns empty array when tickets/ does not exist', () => {
    rmSync(ticketsDir, { recursive: true, force: true })
    const deleted = migrateAutoGeneratedTickets(motiveDir)
    expect(deleted).toEqual([])
  })

  it('returns empty array when no autogen files present', () => {
    writeFileSync(join(ticketsDir, 'hand.md'), '# hand\n\nNo footer.\n', 'utf8')
    const deleted = migrateAutoGeneratedTickets(motiveDir)
    expect(deleted).toEqual([])
  })

  it('handles footer with trailing whitespace on last line', () => {
    const content = `# ticket\n\nbody\n\n${AUTOGEN_FOOTER}   \n`
    writeFileSync(join(ticketsDir, 'trailing.md'), content, 'utf8')
    const deleted = migrateAutoGeneratedTickets(motiveDir)
    expect(deleted).toHaveLength(1)
  })
})
