// Code generated by protoc-gen-go. DO NOT EDIT.
// source: foo.proto

package foo

// Foo is a generated type
type Foo struct {
	// Name is the name field
	Name string
	// Value is the value
	Value int32
}
