// Type declarations for commit-msg-template.mjs

/**
 * Stable marker prefix in the second line of every groundwork-generated commit-msg hook.
 * Full marker line: `# GROUNDWORK-COMMIT-MSG v<version>`
 */
export declare const HOOK_MARKER: string

/**
 * Returns true iff the given file content was generated by groundwork.
 * Version-agnostic — checks only the marker prefix.
 */
export declare function isGroundworkHook(content: string): boolean

export interface CommitMsgHookOptions {
  /** Absolute path to groundwork's hooks/lib directory (from getHooksLibPath()). */
  hooksLibPath: string
  /** Groundwork version string, e.g. "3.1.0". */
  version: string
}

/**
 * Render the portable commit-msg hook for installation into a host repo's
 * .git/hooks/commit-msg. The caller must set mode 0o755 on the written file.
 */
export declare function renderCommitMsgHook(opts: CommitMsgHookOptions): string
