// hooks/lib/motive-tickets.mjs

import {
  readFileSync,
  readdirSync,
  rmSync,
  existsSync,
} from 'node:fs'
import { join } from 'node:path'

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Convert an id (e.g. "S-ANCHOR", "TBD-1", "map-autogen") to a safe filename stem.
 * Lowercases; replaces any char outside [a-z0-9_-] with '-'; collapses runs; trims.
 * Rejects path-traversal attempts (returns null for ids that contain / or ..).
 */
export function sanitizeId(id) {
  if (!id || typeof id !== 'string') return null
  if (id.includes('/') || id.includes('..')) return null
  return id
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-|-$/g, '')
    || null
}

// ---------------------------------------------------------------------------
// Migration
// ---------------------------------------------------------------------------

/**
 * The footer appended by the old per-slice ticket generator.
 * Any tickets/ file that contains this exact string was auto-generated
 * and is safe to delete — hand-authored files will never carry it.
 */
const AUTOGEN_FOOTER = '_Auto-generated — do not edit by hand._'

/**
 * One-shot migration: delete legacy auto-generated ticket files from tickets/.
 *
 * Scans <motiveDir>/tickets/*.md; deletes only those carrying AUTOGEN_FOOTER.
 * Hand-authored files (no footer) are never touched.
 *
 * Reports each deleted path to stdout.
 * Never throws.
 *
 * @param {string} motiveDir — absolute path to .groundwork/motives/<slug>/
 * @returns {string[]} deleted file paths
 */
export function migrateAutoGeneratedTickets(motiveDir) {
  try {
    const ticketsDir = join(motiveDir, 'tickets')
    if (!existsSync(ticketsDir)) return []
    const deleted = []
    for (const file of readdirSync(ticketsDir)) {
      if (!file.endsWith('.md')) continue
      const filePath = join(ticketsDir, file)
      let content
      try { content = readFileSync(filePath, 'utf8') } catch { continue }
      const lastNonEmpty = content.split('\n').map(l => l.trimEnd()).filter(Boolean).at(-1) ?? ''
      if (lastNonEmpty.trim() === AUTOGEN_FOOTER) {
        try {
          rmSync(filePath)
          process.stdout.write(`[motive-tickets] migrate: deleted autogen ticket ${filePath}\n`)
          deleted.push(filePath)
        } catch { /* ignore — file may have been deleted concurrently */ }
      }
    }
    return deleted
  } catch (err) {
    process.stderr.write(
      `[motive-tickets] warn: migration scan failed: ${err?.message ?? err}\n`,
    )
    return []
  }
}


