// Type declarations for motive-tickets.mjs

export interface SliceInput {
  id: string
  status?: string
  desc?: string
  wave?: number
  blocked_by?: string | string[]
  ticket?: string
  [key: string]: unknown
}

export interface OpenItemInput {
  id: string
  kind?: string
  statement?: string
  owner?: string
  blocked_by?: string
  resolved_by?: string
  [key: string]: unknown
}

export interface EventInput {
  ts: string
  type: string
  motive?: string
  msg?: string
  data?: Record<string, unknown>
}

export interface RegenerateOpts {
  slices?: SliceInput[]
  openItems?: OpenItemInput[]
  events?: EventInput[]
}

export declare function regenerateMotiveTickets(motiveDir: string, opts: RegenerateOpts): void

export declare function sanitizeId(id: unknown): string | null

export declare function migrateAutoGeneratedTickets(motiveDir: string): string[]
