// SPDX-License-Identifier: MIT
// Copyright (c) 2024 Example Corp. All rights reserved.

// Code generated by stringer -type=Color. DO NOT EDIT.

//go:build ignore
// +build ignore

// Package directives is a corpus fixture for comment-density autofix tests.
// It contains every Go directive comment that must be exempt from removal.
package directives

// #cgo CFLAGS: -Wall -O2
// #include <stdio.h>
// #include <stdlib.h>
import "C"

import (
	_ "embed"
	"fmt"
	"unsafe"
)

//go:embed dummy.txt
var embeddedContent string

//go:generate stringer -type=Color

// Color represents a display color.
//
//go:generate go run gen.go
type Color int

const (
	// Red is the color red.
	Red Color = iota
	// Green is the color green.
	Green
	// Blue is the color blue.
	Blue
)

//go:linkname runtimeGC runtime.GC
func runtimeGC()

//go:noinline
func doNotInline() int {
	return 42
}

//export GoFunctionName
func GoFunctionName(n C.int) C.int {
	return n + 1
}

// Widget is an API object.
// +kubebuilder:validation:Optional
// +kubebuilder:validation:MaxLength=256
type Widget struct {
	// Name is the widget identifier.
	Name string
}

// nolint
var legacyFlag = true

//nolint:errcheck
var _ = fmt.Sprintf("suppressed") //nolint:errcheck

//lint:ignore SA1000 this is a deliberate test fixture
var deliberate = unsafe.Pointer(nil)

// ExampleDoNotInline shows how to call the function.
func ExampleDoNotInline() {
	fmt.Println(doNotInline())
	// Output:
	// 42
}

// ExampleColor_String shows multi-value output.
func ExampleColor_String() {
	fmt.Println(Red)
	fmt.Println(Green)
	// Unordered output:
	// 0
	// 1
}
