import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, basename } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

type Frontmatter = Record<string, unknown>;

type AgentDefinition = {
	name: string;
	version: string;
	content: string;
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const agentsDir = join(rootDir, "agents-pi");
const outputPath = join(rootDir, "src", "lib", "agent-definitions.generated.ts");
const packageJsonPath = join(rootDir, "package.json");
const shouldCheck = process.argv.includes("--check");

function readPackageVersion(): string {
	const pkg = JSON.parse(readFileSync(packageJsonPath, "utf8")) as { version?: string };
	if (!pkg.version) throw new Error(`Missing version in ${packageJsonPath}`);
	return pkg.version;
}

function splitFrontmatter(source: string): { frontmatter: Frontmatter; body: string } {
	if (!source.startsWith("---\n")) {
		throw new Error("Agent markdown must start with YAML frontmatter");
	}

	const end = source.indexOf("\n---\n", 4);
	if (end === -1) {
		throw new Error("Could not find closing YAML frontmatter delimiter");
	}

	const rawFrontmatter = source.slice(4, end);
	const body = source.slice(end + 5);
	const parsed = yaml.load(rawFrontmatter);
	if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
		throw new Error("Frontmatter must parse to an object");
	}

	return { frontmatter: parsed as Frontmatter, body };
}

function orderedFrontmatter(frontmatter: Frontmatter, version: string): Frontmatter {
	const withManagedFields: Frontmatter = {
		...frontmatter,
		managed_by: "groundwork",
		groundwork_version: version,
	};

	const preferredOrder = [
		"name",
		"description",
		"model",
		"thinking",
		"mode",
		"enabled",
		"prompt_mode",
		"tools",
		"permission",
		"managed_by",
		"groundwork_version",
	];

	const ordered: Frontmatter = {};
	for (const key of preferredOrder) {
		if (key in withManagedFields) ordered[key] = withManagedFields[key];
	}
	for (const [key, value] of Object.entries(withManagedFields)) {
		if (!(key in ordered)) ordered[key] = value;
	}
	return ordered;
}

function stringifyFrontmatter(frontmatter: Frontmatter): string {
	return yaml.dump(frontmatter, {
		lineWidth: -1,
		noRefs: true,
		quotingType: '"',
		forceQuotes: false,
	}).trimEnd();
}

function buildContent(frontmatter: Frontmatter, body: string, version: string): string {
	const normalizedBody = body.replace(/^\n+/, "");
	return `---\n${stringifyFrontmatter(orderedFrontmatter(frontmatter, version))}\n---\n\n${normalizedBody}`;
}

function escapeTemplateLiteral(text: string): string {
	return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function readAgentDefinitions(version: string): AgentDefinition[] {
	const entries = readdirSync(agentsDir, { withFileTypes: true })
		.filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
		.map((entry) => entry.name)
		.sort();

	const names = new Set<string>();
	const definitions = entries.map((fileName) => {
		const source = readFileSync(join(agentsDir, fileName), "utf8");
		const { frontmatter, body } = splitFrontmatter(source);
		const name = typeof frontmatter.name === "string" ? frontmatter.name : basename(fileName, ".md");
		if (names.has(name)) throw new Error(`Duplicate agent name: ${name}`);
		names.add(name);
		return {
			name,
			version,
			content: buildContent(frontmatter, body, version),
		};
	});

	return [
		{
			name: "Explore",
			version,
			content: `---\nenabled: false\nmanaged_by: groundwork\ngroundwork_version: "${version}"\n---\n\nDisabled by groundwork — use \`explore\` instead.\n`,
		},
		{
			name: "Plan",
			version,
			content: `---\nenabled: false\nmanaged_by: groundwork\ngroundwork_version: "${version}"\n---\n\nDisabled by groundwork.\n`,
		},
		...definitions,
	];
}

function renderModule(version: string, definitions: AgentDefinition[]): string {
	const items = definitions
		.map(
			(def) => `\t{\n\t\tname: ${JSON.stringify(def.name)},\n\t\tversion: ${JSON.stringify(def.version)},\n\t\tcontent: \`${escapeTemplateLiteral(def.content)}\`,\n\t},`,
		)
		.join("\n\n");

	return `// AUTO-GENERATED by scripts/generate-agent-definitions.ts
// Do not edit this file directly. Edit agents-pi/*.md and re-run \`pnpm run generate:agents\`.

import type { AgentDefinition } from "./agent-definitions.js";

export const GROUNDWORK_VERSION = ${JSON.stringify(version)};

export const EMBEDDED_AGENTS: AgentDefinition[] = [
${items}
];
`;
}

function main() {
	const version = readPackageVersion();
	const rendered = renderModule(version, readAgentDefinitions(version));

	if (shouldCheck) {
		const current = readFileSync(outputPath, "utf8");
		if (current !== rendered) {
			console.error(`Generated file is stale: ${outputPath}`);
			process.exitCode = 1;
		}
		return;
	}

	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, rendered);
}

main();
