/**
 * autofix-go-directives.test.ts
 *
 * AC2 – positive control: every protected Go directive comment is detected as exempt.
 * AC3 – property: autoFix never removes an exempt comment and never corrupts code.
 * AC4 – at least half of property iterations trigger removed>0.
 * AC5 – every corpus file is tracked by git (not swallowed by .gitignore).
 */

import { describe, it, expect } from "bun:test";
import path from "node:path";
import { readFileSync, readdirSync } from "node:fs";
import { execSync } from "node:child_process";
import {
  findComments,
  autoFix,
  stripComments,
  type Comment,
} from "../../src/hooks/lib/comment-density.js";

const FIXTURE_DIR = path.join(
  import.meta.dir,
  "../fixtures/comment-density/go-directives",
);
const CORPUS_FILE = path.join(FIXTURE_DIR, "corpus.go");
const REPO_ROOT = path.resolve(import.meta.dir, "../../../..");

// ─── helpers ────────────────────────────────────────────────────────────────

function mulberry32(seed: number): () => number {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

async function countErrorNodes(
  text: string,
): Promise<number> {
  const { getParser: gp } = await import(
    "../../src/hooks/lib/tree-sitter-loader.js"
  );
  const r = await gp("go");
  if (!r.ok) throw new Error(r.reason);
  const tree = r.parser.parse(text);
  let count = 0;
  function walk(node: import("../../src/hooks/lib/tree-sitter.js").Node): void {
    if (node.type === "ERROR") count++;
    for (let i = 0; i < node.childCount; i++) {
      const child = node.child(i);
      if (child) walk(child);
    }
  }
  walk(tree.rootNode);
  return count;
}

function codeTokens(text: string, comments: Comment[]): string {
  // Strip all comments, then normalize whitespace to compare code content.
  const { text: stripped } = stripComments(text, comments);
  return stripped.replace(/\s+/g, " ").trim();
}

// ─── Shared directive table (used by AC2 and AC3) ────────────────────────────

// Each entry describes one protected directive comment that must never be
// removed by autoFix.
//
const DIRECTIVES: Array<{
  name: string;
  text: string;
  exemptReason?: string;
  docNote?: string;
}> = [
  { name: "go:build",        text: "//go:build ignore",
    docNote: "go-file-header (before package clause)" },
  { name: "// +build",       text: "// +build ignore",
    docNote: "go-file-header (before package clause)" },
  { name: "Code generated",  text: "// Code generated by stringer -type=Color. DO NOT EDIT.",
    docNote: "go-file-header (before package clause)" },
  { name: "SPDX",            text: "// SPDX-License-Identifier: MIT",
    docNote: "go-file-header (before package clause)" },

  { name: "go:generate",     text: "//go:generate stringer -type=Color",
    exemptReason: "go:generate stringer -type=Col" },

  { name: "go:embed",        text: "//go:embed dummy.txt",
    docNote: "go:embed dummy.txt (GO_DIRECTIVE_RE; must sit above var declaration)" },
  { name: "go:linkname",     text: "//go:linkname runtimeGC runtime.GC",
    docNote: "go:linkname runtimeGC runtime. (GO_DIRECTIVE_RE; must sit above func)" },
  { name: "go:noinline",     text: "//go:noinline",
    docNote: "go:noinline (GO_DIRECTIVE_RE; must sit above func)" },
  { name: "export",          text: "//export GoFunctionName",
    docNote: "export GoFunctionName (GO_EXPORT_RE; must sit above func)" },

  { name: "#cgo preamble",   text: "// #cgo CFLAGS: -Wall -O2",
    exemptReason: "cgo-preamble" },
  { name: "#include preamble", text: "// #include <stdio.h>",
    exemptReason: "cgo-preamble" },

  { name: "Output:",         text: "// Output:",
    exemptReason: "go-example-output" },
  { name: "Unordered output:", text: "// Unordered output:",
    exemptReason: "go-example-output" },

  { name: "nolint (space)",  text: "// nolint",
    exemptReason: "nolint" },
  { name: "nolint:errcheck", text: "//nolint:errcheck",
    exemptReason: "nolint:errcheck" },
  { name: "lint:ignore",     text: "//lint:ignore SA1000 this is a deliberate test fixture",
    exemptReason: "lint:ignore SA1000 this is a d" },

  { name: "+kubebuilder",    text: "// +kubebuilder:validation:Optional",
    exemptReason: "+kubebuilder:validation:Option" },

  { name: "doc comment",     text: "// Color represents a display color.",
    docNote: "go-doc (isGoDocComment traverses to type Color declaration)" },
];

// ─── AC2: positive control ───────────────────────────────────────────────────

describe("AC2: Go directive corpus — per-directive exemption", () => {
  const corpusText = readFileSync(CORPUS_FILE, "utf8");

  for (const { name, text, exemptReason } of DIRECTIVES) {
    it(`"${name}" is present in corpus and is exempt`, async () => {
      // 1. text is in corpus source
      expect(corpusText).toContain(text);

      // 2. findComments returns a comment containing it
      const r = await findComments(corpusText, "go");
      if (!r.ok) throw new Error(`findComments failed: ${r.reason}`);

      const found = r.comments.find((c) => c.text.includes(text));
      expect(found).toBeDefined();
      if (!found) return;

      // 3. the comment is exempt
      expect(found.exempt).toBe(true);

      if (exemptReason !== undefined) {
        expect(found.exemptReason, `wrong exemptReason for "${name}"`).toBe(exemptReason);
      }
    });
  }
});

// ─── AC3: property — autoFix never removes a protected comment ───────────────

describe(
  "AC3: property — autoFix never removes exempt comments or corrupts code",
  () => {
    it(
      "50 seeded iterations across addedRow strategies",
      async () => {
        const corpusText = readFileSync(CORPUS_FILE, "utf8");

        let removedGtZeroCount = 0;

        const SEEDS = [
          0x1, 0x2, 0x3, 0x5, 0x8, 0x13, 0x21, 0x34, 0x55, 0x89,
          0x144, 0x233, 0x377, 0x610, 0x987, 0x1597, 0x2584, 0x4181,
          0x6765, 0xabcd, 0xdead, 0xbeef, 0x1234, 0x5678, 0x9abc,
          0xdef0, 0x1111, 0x2222, 0x3333, 0x4444, 0x5555, 0x6666,
          0x7777, 0x8888, 0x9999, 0xaaaa, 0xbbbb, 0xcccc, 0xdddd,
          0xeeee, 0xffff, 0x0101, 0x0202, 0x0303, 0x0404, 0x0505,
          0x0606, 0x0707, 0x0808, 0x0909,
        ]; // 50 seeds

        expect(SEEDS.length).toBe(50);

        for (let iter = 0; iter < SEEDS.length; iter++) {
          const rng = mulberry32(SEEDS[iter]);

          // Build a modified text: inject 25 narrative (non-exempt) comments
          // inside a synthetic function appended to the corpus. This guarantees
          // the injected comments are non-exempt and always valid Go syntax.
          const numComments = 20 + Math.floor(rng() * 20); // 20–39 comments
          const commentLines = Array.from(
            { length: numComments },
            (_, i) => `\t// narrative comment iter=${iter} idx=${i}`,
          );
          const syntheticFunc =
            `\nfunc syntheticIter${iter}() {\n` +
            commentLines.join("\n") +
            `\n\t_ = legacyFlag\n}\n`;

          const text = corpusText + syntheticFunc;

          // addedRow strategy: alternate between all-rows and 50%-rows
          const lines = text.split("\n");
          let addedRows: Set<number>;
          const strategy = iter % 3;
          if (strategy === 0) {
            // all rows
            addedRows = new Set(lines.map((_, i) => i));
          } else if (strategy === 1) {
            // random ~50% of rows
            addedRows = new Set(
              lines.map((_, i) => i).filter(() => rng() < 0.5),
            );
          } else {
            addedRows = new Set<number>();
            let i = 0;
            while (i < lines.length) {
              if (rng() < 0.4) {
                const hunkLen = 1 + Math.floor(rng() * 10);
                for (let j = i; j < Math.min(i + hunkLen, lines.length); j++) {
                  addedRows.add(j);
                }
                i += hunkLen + Math.floor(rng() * 5);
              } else {
                i++;
              }
            }
          }

          if (addedRows.size === 0) {
            for (
              let i = lines.length - numComments - 5;
              i < lines.length;
              i++
            ) {
              if (i >= 0) addedRows.add(i);
            }
          }

          const result = await autoFix(text, "go", addedRows);

          if (!result.ok) {
            continue;
          }

          if (result.removed > 0) removedGtZeroCount++;

          const fixed = result.fixed;

          for (const { text: protectedText } of DIRECTIVES) {
            if (!text.includes(protectedText)) continue;
            expect(fixed, `protected text "${protectedText}" removed by autoFix`).toContain(protectedText);
          }

          const inputParsed = await findComments(text, "go");
          expect(inputParsed.ok).toBe(true);
          if (!inputParsed.ok) continue;

          const fixedParsed = await findComments(fixed, "go");
          expect(fixedParsed.ok).toBe(true);
          if (!fixedParsed.ok) continue;

          const inputTokens = codeTokens(text, inputParsed.comments);
          const fixedTokens = codeTokens(fixed, fixedParsed.comments);
          expect(fixedTokens).toBe(inputTokens);

          const errorsAfter = await countErrorNodes(fixed);
          expect(errorsAfter).toBe(0);
        }

        console.log(
          `[AC3/AC4] iterations with removed>0: ${removedGtZeroCount}/50`,
        );
        expect(removedGtZeroCount).toBeGreaterThanOrEqual(25);
      },
    );
  },
);

// ─── AC4: explicit removed>0 count assertion ─────────────────────────────────

describe("AC4: removed>0 count", () => {
  it(
    "at least 25 of 50 property iterations trigger removal",
    async () => {
      const corpusText = readFileSync(CORPUS_FILE, "utf8");
      let removedGtZeroCount = 0;

      const seeds = Array.from({ length: 50 }, (_, i) => (i + 1) * 0x1234);
      for (let iter = 0; iter < seeds.length; iter++) {
        const rng = mulberry32(seeds[iter]);
        const numComments = 20 + Math.floor(rng() * 20);
        const commentLines = Array.from(
          { length: numComments },
          (_, i) => `\t// ac4 comment iter=${iter} idx=${i}`,
        );
        const syntheticFunc =
          `\nfunc ac4Iter${iter}() {\n` +
          commentLines.join("\n") +
          `\n\t_ = legacyFlag\n}\n`;

        const text = corpusText + syntheticFunc;
        const addedRows = new Set(text.split("\n").map((_, i) => i));
        const result = await autoFix(text, "go", addedRows);
        if (result.ok && result.removed > 0) removedGtZeroCount++;
      }

      console.log(`[AC4] removed>0 in ${removedGtZeroCount}/50 iterations`);
      expect(removedGtZeroCount).toBeGreaterThanOrEqual(25);
    },
  );
});

// ─── AC5: corpus files are not gitignored ────────────────────────────────────

describe("AC5: corpus files are not gitignored", () => {
  it("fixture dir is non-empty and no corpus file is ignored", () => {
    const corpusFiles = readdirSync(FIXTURE_DIR).map((f) =>
      path.join(FIXTURE_DIR, f),
    );
    expect(corpusFiles.length).toBeGreaterThan(0);

    for (const f of corpusFiles) {
      let exitCode: number | null = null;
      try {
        execSync(`git check-ignore --no-index -q "${f}"`, {
          cwd: REPO_ROOT,
          encoding: "utf8",
        });
        exitCode = 0;
      } catch (e: unknown) {
        exitCode = (e as { status?: number }).status ?? null;
      }
      expect(exitCode, `${f} is gitignored`).toBe(1);
    }
  });
});
