/**
 * guard-go.test.ts — PreToolUse guard keeps Go directives.
 *
 * AC1: Write of a new Go file containing every corpus directive plus over-budget
 *      narrative comments → updatedInput exists; every directive text survives.
 * AC2: In that same updatedInput, at least one narrative comment is stripped.
 * AC3: Edit adding over-budget narrative comments next to a #cgo preamble and
 *      an Example Output: block (both in old context). Old lines survive;
 *      at least one narrative is stripped.
 * AC4: Evidence (not assertion) that guard output for a gofmt-clean input
 *      stays gofmt-clean.
 */

import { describe, it, expect, beforeAll } from "bun:test";
import { mkdtempSync, readFileSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import { check } from "../../src/hooks/guard.js";

// ─── isolation ──────────────────────────────────────────────────────────────
// Point CLAUDE_PROJECT_DIR and cwd at a temp dir (not a git repo) so the guard
// never reads the real project tree.

const TEMP_DIR = mkdtempSync(path.join(os.tmpdir(), "guard-go-"));

process.env.CLAUDE_PROJECT_DIR = TEMP_DIR;

// ─── helpers ─────────────────────────────────────────────────────────────────

function writePayload(filePath: string, content: string) {
  return {
    tool_name: "Write",
    tool_input: { file_path: filePath, content },
    cwd: TEMP_DIR,
  };
}

function editPayload(filePath: string, old_string: string, new_string: string) {
  return {
    tool_name: "Edit",
    tool_input: { file_path: filePath, old_string, new_string },
    cwd: TEMP_DIR,
  };
}

function getHso(r: { stdout: string }): Record<string, unknown> {
  const s = r.stdout.trim();
  if (!s) return {};
  const parsed = JSON.parse(s) as Record<string, unknown>;
  return (parsed.hookSpecificOutput as Record<string, unknown>) ?? {};
}

// ─── fixtures ─────────────────────────────────────────────────────────────────

const CORPUS_FILE = path.join(
  import.meta.dir,
  "../fixtures/comment-density/go-directives/corpus.go",
);
const CORPUS_TEXT = readFileSync(CORPUS_FILE, "utf8");

// All directive texts that must survive stripping.
const DIRECTIVES: Array<{ name: string; text: string }> = [
  { name: "go:build",              text: "//go:build ignore" },
  { name: "+build",                text: "// +build ignore" },
  { name: "go:generate (stringer)",text: "//go:generate stringer -type=Color" },
  { name: "go:embed",              text: "//go:embed dummy.txt" },
  { name: "go:linkname",           text: "//go:linkname runtimeGC runtime.GC" },
  { name: "go:noinline",           text: "//go:noinline" },
  { name: "export",                text: "//export GoFunctionName" },
  { name: "#cgo preamble",         text: "// #cgo CFLAGS: -Wall -O2" },
  { name: "#include preamble",     text: "// #include <stdio.h>" },
  { name: "Output:",               text: "// Output:" },
  { name: "Unordered output:",     text: "// Unordered output:" },
  { name: "nolint (space)",        text: "// nolint" },
  { name: "nolint:errcheck",       text: "//nolint:errcheck" },
  { name: "lint:ignore",           text: "//lint:ignore SA1000 this is a deliberate test fixture" },
  { name: "Code generated",        text: "// Code generated by stringer -type=Color. DO NOT EDIT." },
  { name: "SPDX",                  text: "// SPDX-License-Identifier: MIT" },
  { name: "+kubebuilder",          text: "// +kubebuilder:validation:Optional" },
];

// A distinctive narrative comment we'll assert is absent after stripping.
const NARRATIVE_SENTINEL = "// NARRATIVE_GUARD_GO_SENTINEL this line should be stripped by guard";

// Build the Write content: corpus + a synthetic function with many narrative
// comments to push well over the 5% budget.
const NARRATIVE_BLOCK = Array.from(
  { length: 40 },
  (_, i) =>
    i === 39
      ? NARRATIVE_SENTINEL
      : `// narrative filler line ${i}`,
).join("\n");

const WRITE_CONTENT =
  CORPUS_TEXT +
  `\nfunc narrativeBlock() {\n${NARRATIVE_BLOCK}\n}\n`;

// ─── AC1 + AC2 ────────────────────────────────────────────────────────────────

describe("AC1 + AC2: Write of new Go file with directives and over-budget narratives", () => {
  let hso: Record<string, unknown>;
  let content: string;

  beforeAll(async () => {
    const filePath = path.join(TEMP_DIR, "corpus_write.go");
    // readFile returns null → new file → guard proceeds without pre-content
    const r = await check(writePayload(filePath, WRITE_CONTENT), {
      readFile: () => null,
    });
    hso = getHso(r);
    const ui = hso.updatedInput as Record<string, unknown> | undefined;
    content = typeof ui?.content === "string" ? ui.content : "";
  });

  it("AC1: positive control — updatedInput is present", () => {
    expect(hso).toHaveProperty("updatedInput");
  });

  for (const { name, text } of DIRECTIVES) {
    it(`AC1: directive "${name}" survives in updatedInput.content`, () => {
      expect(content).toContain(text);
    });
  }

  it("AC2: narrative sentinel is absent from updatedInput.content (stripped)", () => {
    // Positive signal: it was present in the input
    expect(WRITE_CONTENT).toContain(NARRATIVE_SENTINEL);
    // Guard strips it
    expect(content).not.toContain(NARRATIVE_SENTINEL);
  });
});

// ─── AC3 ─────────────────────────────────────────────────────────────────────

describe("AC3: Edit adding narratives next to #cgo preamble and Output: block (old context)", () => {
  // Pre-existing file content: a file with a cgo preamble + an Example function.
  const PRE_CONTENT = `// Package example uses cgo and has test examples.
package example

// #cgo CFLAGS: -Wall
// #include <stdio.h>
import "C"

// ExampleHello shows hello world.
func ExampleHello() {
\t// Output:
\t// hello
}

func Placeholder() {}
`;

  const OLD_STRING = `func Placeholder() {}`;

  const NEW_NARRATIVES = Array.from(
    { length: 40 },
    (_, i) =>
      i === 0
        ? "\t// AC3_NARRATIVE_SENTINEL to be stripped"
        : `\t// ac3 narrative filler ${i}`,
  ).join("\n");

  const NEW_STRING = `func Placeholder() {\n${NEW_NARRATIVES}\n}`;

  let hso: Record<string, unknown>;

  beforeAll(async () => {
    const filePath = path.join(TEMP_DIR, "ac3_edit.go");
    const r = await check(
      editPayload(filePath, OLD_STRING, NEW_STRING),
      { readFile: () => PRE_CONTENT },
    );
    hso = getHso(r);
  });

  it("AC3: updatedInput is present (guard triggered)", () => {
    expect(hso).toHaveProperty("updatedInput");
  });

  it("AC3: #cgo and Output: survive (they are in old context, not stripped)", () => {
    const ui = hso.updatedInput as Record<string, unknown> | undefined;
    expect(ui).toBeDefined();
    const newStr = typeof ui!.new_string === "string" ? ui!.new_string : "";
    const postEdit = PRE_CONTENT.replace(OLD_STRING, newStr);
    expect(postEdit).toContain("// #cgo CFLAGS:");
    expect(postEdit).toContain("// Output:");
  });

  it("AC3: narrative filler 39 (last, over budget) is absent from updatedInput.new_string", () => {
    const ui = hso.updatedInput as Record<string, unknown> | undefined;
    expect(ui).toBeDefined();
    const newStr = typeof ui!.new_string === "string" ? ui!.new_string : "";
    expect(NEW_STRING).toContain("ac3 narrative filler 39");
    expect(newStr).not.toContain("ac3 narrative filler 39");
  });

  it("AC3 FINDING: #cgo and Output: byte-identical in post-edit; at least one narrative line stripped from new_string", () => {
    const ui = hso.updatedInput as Record<string, unknown> | undefined;
    expect(ui).toBeDefined();
    const newStr = typeof ui!.new_string === "string" ? ui!.new_string : "";
    const postEdit = PRE_CONTENT.replace(OLD_STRING, newStr);
    expect(postEdit).toContain("// #cgo CFLAGS: -Wall");
    expect(postEdit).toContain("// Output:");
    expect(newStr).not.toContain("ac3 narrative filler 39");
  });
});

it.todo("guard output gofmt-clean for Go — follow-up (a)", () => {});
