/**
 * T8 consolidated AC coverage — migration + missing AC tests
 *
 * Covers:
 *   T8-AC1  migration deletes only auto-generated ticket files (AUTOGEN_FOOTER)
 *   T8-AC2  motive with no ticket corpus works end-to-end (no errors, MAP renders)
 *   T2-AC2  'ticket' in KNOWN_SLICE_KEYS — typo 'tickte' produces near-miss warning
 *   T6-AC1  DECISION event without data.id emits a loud warning (warn, not block)
 *
 * T3-AC3, T4-AC1 — see test/motive-ticket-doc.test.ts and test/motive-tickets.test.ts
 * T5-AC3         — see test/hooks/motive-tickets.test.ts (SC3 T5-AC3)
 * T5-AC4         — see test/hooks/motive-map.test.ts (T5-AC4)
 */

// @ts-nocheck
import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import {
  mkdtempSync,
  mkdirSync,
  writeFileSync,
  readFileSync,
  existsSync,
  rmSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'
import { migrateAutoGeneratedTickets, regenerateMotiveTickets } from '../../hooks/lib/motive-tickets.mjs'
import { regenerateMotiveMap } from '../../hooks/lib/motive-map.mjs'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const ROOT = new URL('../../', import.meta.url).pathname.replace(/\/$/, '')
const LEDGER_CLI = join(ROOT, 'hooks', 'ledger.mjs')
const JOURNAL_CLI = join(ROOT, 'hooks', 'journal.mjs')

function tmp() {
  return mkdtempSync(join(tmpdir(), 'gw-t8-test-'))
}

function makeLedgerEnv(dir: string): Record<string, string> {
  return {
    ...process.env,
    CLAUDE_PROJECT_DIR: dir,
    GROUNDWORK_RUN_ID: 'test-run',
  }
}

function makeJournalEnv(dir: string): Record<string, string> {
  return {
    ...process.env,
    CLAUDE_PROJECT_DIR: dir,
    JOURNAL_SESSION_ID: 'test-t8',
  }
}

function runLedger(args: string[], env: Record<string, string>) {
  return spawnSync(process.execPath, [LEDGER_CLI, ...args], {
    encoding: 'utf8',
    env,
  })
}

function runJournal(args: string[], env: Record<string, string>) {
  return spawnSync(process.execPath, [JOURNAL_CLI, ...args], {
    encoding: 'utf8',
    env,
  })
}

/** Seed a minimal run ledger so ledger CLI can operate. */
function initLedger(dir: string) {
  const runsDir = join(dir, '.groundwork', 'runs')
  mkdirSync(runsDir, { recursive: true })
  // ledger init writes to stdout the write token; we just call it
  const r = runLedger(['init', '--motive', 'test'], makeLedgerEnv(dir))
  return r
}

// ---------------------------------------------------------------------------
// T8-AC1 — migration deletes only auto-generated ticket files
// ---------------------------------------------------------------------------

const AUTOGEN_FOOTER = '_Auto-generated — do not edit by hand._'

describe('T8-AC1 — migrateAutoGeneratedTickets', () => {
  let dir: string

  beforeEach(() => { dir = tmp() })
  afterEach(() => { rmSync(dir, { recursive: true, force: true }) })

  it('deletes a file that carries the auto-generated footer and reports the path', () => {
    mkdirSync(join(dir, 'tickets'), { recursive: true })
    const filePath = join(dir, 'tickets', 't1.md')
    writeFileSync(filePath, `# T1: some slice\n\n---\n${AUTOGEN_FOOTER}\n`, 'utf8')

    const deleted = migrateAutoGeneratedTickets(dir)

    expect(deleted).toHaveLength(1)
    expect(deleted[0]).toBe(filePath)
    expect(existsSync(filePath)).toBe(false)
  })

  it('leaves a hand-authored file (no footer) untouched', () => {
    mkdirSync(join(dir, 'tickets'), { recursive: true })
    const filePath = join(dir, 'tickets', 'T1.md')
    const handAuthored = '# T1: my hand-written ticket\n\nPrecious content.\n'
    writeFileSync(filePath, handAuthored, 'utf8')

    const deleted = migrateAutoGeneratedTickets(dir)

    expect(deleted).toHaveLength(0)
    expect(readFileSync(filePath, 'utf8')).toBe(handAuthored)
  })

  it('returns empty array when tickets/ does not exist — never throws', () => {
    expect(() => migrateAutoGeneratedTickets(dir)).not.toThrow()
    expect(migrateAutoGeneratedTickets(dir)).toEqual([])
  })

  it('deletes only autogen files, preserves hand-authored sibling', () => {
    mkdirSync(join(dir, 'tickets'), { recursive: true })
    const autogenPath = join(dir, 'tickets', 'S1.md')
    const handPath = join(dir, 'tickets', 'T1.md')
    writeFileSync(autogenPath, `# S1\n\n---\n${AUTOGEN_FOOTER}\n`, 'utf8')
    writeFileSync(handPath, '# T1: hand-authored\n\nContent.\n', 'utf8')

    const deleted = migrateAutoGeneratedTickets(dir)

    expect(deleted).toHaveLength(1)
    expect(deleted[0]).toBe(autogenPath)
    expect(existsSync(autogenPath)).toBe(false)
    expect(existsSync(handPath)).toBe(true)
  })

  it('handles a non-md file gracefully — only processes .md files', () => {
    mkdirSync(join(dir, 'tickets'), { recursive: true })
    writeFileSync(join(dir, 'tickets', 'README.txt'), AUTOGEN_FOOTER, 'utf8')

    const deleted = migrateAutoGeneratedTickets(dir)

    expect(deleted).toHaveLength(0)
  })

  it('never throws when motiveDir is invalid', () => {
    expect(() => migrateAutoGeneratedTickets('/nonexistent/path/xyz')).not.toThrow()
  })
})

// ---------------------------------------------------------------------------
// T8-AC2 — motive with no ticket corpus works end-to-end
// ---------------------------------------------------------------------------

describe('T8-AC2 — zero-ticket motive end-to-end', () => {
  let dir: string

  beforeEach(() => { dir = tmp() })
  afterEach(() => { rmSync(dir, { recursive: true, force: true }) })

  it('regenerateMotiveTickets + regenerateMotiveMap produce no errors and MAP renders', () => {
    // Motive dir with charter but zero tickets and zero open items
    const motiveDir = join(dir, '.groundwork', 'motives', 'm')
    mkdirSync(motiveDir, { recursive: true })
    writeFileSync(join(motiveDir, 'motive.md'), '# motive: m\n\n## Objective\nTest.\n', 'utf8')

    const runsDir = join(dir, '.groundwork', 'runs')
    mkdirSync(runsDir, { recursive: true })
    writeFileSync(join(runsDir, 'run-test.json'), JSON.stringify({
      motive: 'm',
      active: true,
      slices: [],
      gate: {},
    }), 'utf8')

    // No open items, no slices
    expect(() => {
      regenerateMotiveTickets(motiveDir, { slices: [], openItems: [], events: [] })
    }).not.toThrow()

    expect(() => {
      regenerateMotiveMap(dir, 'm')
    }).not.toThrow()

    // MAP.md must exist and be non-empty
    const mapPath = join(motiveDir, 'MAP.md')
    expect(existsSync(mapPath)).toBe(true)
    expect(readFileSync(mapPath, 'utf8').length).toBeGreaterThan(0)

    // tickets/ must NOT have been created
    expect(existsSync(join(motiveDir, 'tickets'))).toBe(false)
  })
})

// ---------------------------------------------------------------------------
// T2-AC2 — 'ticket' is in KNOWN_SLICE_KEYS (typo guard)
// ---------------------------------------------------------------------------

describe('T2-AC2 — ledger KNOWN_SLICE_KEYS includes ticket', () => {
  it('ledger source declares ticket in KNOWN_SLICE_KEYS so typos trigger the near-miss guard', () => {
    // Static source proof: 'ticket' must appear as a string literal inside the
    // KNOWN_SLICE_KEYS Set definition in hooks/ledger.mjs.
    // This is the authoritative check — it proves the near-miss guard (Levenshtein ≤2)
    // will fire for typos like 'tickte' rather than silently ignoring them.
    const ledgerSrc = readFileSync(join(ROOT, 'hooks', 'ledger.mjs'), 'utf8')

    // Isolate the KNOWN_SLICE_KEYS block (from declaration to closing paren of Set)
    const startIdx = ledgerSrc.indexOf('const KNOWN_SLICE_KEYS')
    expect(startIdx).toBeGreaterThan(-1)
    const endIdx = ledgerSrc.indexOf('])', startIdx)
    expect(endIdx).toBeGreaterThan(startIdx)
    const keysBlock = ledgerSrc.slice(startIdx, endIdx + 2)

    expect(keysBlock).toContain("'ticket'")
    expect(keysBlock).toContain("'covers_ac'")
  })
})

// ---------------------------------------------------------------------------
// T6-AC1 — id-less DECISION emits loud warning without blocking
// ---------------------------------------------------------------------------

describe('T6-AC1 — journal DECISION without data.id warns loudly', () => {
  let dir: string

  beforeEach(() => {
    dir = tmp()
    mkdirSync(join(dir, '.groundwork', 'journal'), { recursive: true })
  })
  afterEach(() => { rmSync(dir, { recursive: true, force: true }) })

  it('appending a DECISION without data.id exits 2 naming the missing key (ARTIFACT-R-004)', () => {
    const result = runJournal(
      [
        'append',
        '--type', 'DECISION',
        '--motive', 'm',
        '--msg', 'We decided to do X',
        '--data', JSON.stringify({
          decision: 'Use approach X',
          rationale: 'It is simpler',
          // NOTE: no 'id' field
        }),
      ],
      makeJournalEnv(dir),
    )

    // ARTIFACT-R-004: id-less DECISION is now a hard error (exit 2)
    expect(result.stderr).toContain('data.id')
    expect(result.status).toBe(2)
  })

  it('appending a DECISION WITH data.id does NOT emit the id-less warning', () => {
    const result = runJournal(
      [
        'append',
        '--type', 'DECISION',
        '--motive', 'm',
        '--msg', 'We decided to do Y',
        '--data', JSON.stringify({
          id: 'D-42',
          decision: 'Use approach Y',
          rationale: 'It is faster',
        }),
      ],
      makeJournalEnv(dir),
    )

    expect(result.stderr).not.toMatch(/WARNING.*DECISION.*no.*id|DECISION.*has no data\.id/i)
    expect(result.status).toBe(0)
  })
})
