/**
 * Tests for the rfc manifest feature:
 *   - `rfc index <dir>` generates the manifest block in rfc.md
 *   - `rfc validate` detects stale manifests (freshness enforcement)
 *   - `rfc new` scaffolds a fresh manifest automatically
 *   - generateManifestBlock / extractManifestBlock round-trip
 *
 * Mutation tests included:
 *   M-M01: equality boundary — manifest comparison uses strict equality
 *   M-M02: staleness detection — a single changed token count triggers failure
 *   M-M03: missing-section detection — a new section file causes stale
 *   M-M04: schema gate — schema:1 RFCs are NOT freshness-checked
 */

import {
	execFileSync,
} from "node:child_process";
import {
	existsSync,
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
	generateManifestBlock,
	extractManifestBlock,
	writeManifest,
} from "../../hooks/lib/rfc-io.mjs";

const CLI = path.resolve(import.meta.dirname, "..", "..", "hooks", "rfc.mjs");

let projectDir: string;

beforeEach(() => {
	projectDir = mkdtempSync(path.join(tmpdir(), "gw-rfc-manifest-"));
});
afterEach(() => rmSync(projectDir, { recursive: true, force: true }));

function run(args: string[]): { code: number; stdout: string; stderr: string } {
	const env = { ...process.env, CLAUDE_PROJECT_DIR: projectDir };
	try {
		const stdout = execFileSync("node", [CLI, ...args], { env, encoding: "utf8" });
		return { code: 0, stdout, stderr: "" };
	} catch (e: any) {
		return { code: e.status ?? 1, stdout: e.stdout ?? "", stderr: e.stderr ?? "" };
	}
}

function rfcsDir() {
	return path.join(projectDir, ".groundwork", "rfcs");
}

function createRfc(slug = "test-feature"): string {
	const r = run(["new", slug]);
	expect(r.code).toBe(0);
	const match = r.stdout.match(/Created (.+)/);
	expect(match).toBeTruthy();
	return match![1].trim();
}

/**
 * Build a minimal schema-2 RFC directory with the given section files.
 * sections is a map of relative path under sections/ → file content.
 */
function makeRfc(slug: string, sections: Record<string, string>): string {
	const dir = path.join(rfcsDir(), `0001-${slug}`);
	mkdirSync(dir, { recursive: true });
	mkdirSync(path.join(dir, "sections"), { recursive: true });
	mkdirSync(path.join(dir, "notes"), { recursive: true });
	mkdirSync(path.join(dir, "reviews"), { recursive: true });
	writeFileSync(path.join(dir, "tasks.yaml"), "[]\n");
	for (const [rel, content] of Object.entries(sections)) {
		const full = path.join(dir, "sections", rel);
		mkdirSync(path.dirname(full), { recursive: true });
		writeFileSync(full, content);
	}
	// Write rfc.md with markers but no content (before index)
	const fm = [
		"---",
		"schema: 2",
		"uid: R-20260726-AAAAAA",
		"ordinal: 1",
		`slug: ${slug}`,
		`title: ${slug}`,
		"status: draft",
		"classification: tactical",
		`created: "2026-07-26T00:00:00.000Z"`,
		`updated: "2026-07-26T00:00:00.000Z"`,
		"accepted_at: null",
		"accepted_by: null",
		"supersedes: []",
		"superseded_by: null",
		"body_digest: null",
		"spec_delta: []",
		"---",
		"",
		"> Abstract: TODO",
		"",
		"<!-- rfc:manifest:begin — generated by `rfc index`; do not hand-edit -->",
		"<!-- rfc:manifest:end -->",
		"",
	].join("\n");
	writeFileSync(path.join(dir, "rfc.md"), fm);
	return dir;
}

// ---------------------------------------------------------------------------
// generateManifestBlock unit tests
// ---------------------------------------------------------------------------

describe("generateManifestBlock", () => {
	it("returns null when sections/ does not exist", () => {
		const dir = mkdtempSync(path.join(tmpdir(), "gw-mfst-"));
		try {
			expect(generateManifestBlock(dir)).toBeNull();
		} finally {
			rmSync(dir, { recursive: true, force: true });
		}
	});

	it("generates begin/end markers", () => {
		const rfcDir = makeRfc("demo", { "01-summary.md": "## 1. Summary\n\nHello\n" });
		const block = generateManifestBlock(rfcDir)!;
		expect(block).toContain("<!-- rfc:manifest:begin");
		expect(block).toContain("<!-- rfc:manifest:end -->");
	});

	it("generates a row for each numbered file", () => {
		const rfcDir = makeRfc("demo", {
			"01-summary.md": "## 1. Summary\n\nHello\n",
			"02-motivation.md": "## 2. Motivation\n\nWorld\n",
		});
		const block = generateManifestBlock(rfcDir)!;
		expect(block).toContain("| 1 | Summary |");
		expect(block).toContain("| 2 | Motivation |");
	});

	it("generates directory aggregate row + child rows", () => {
		const rfcDir = makeRfc("demo", {
			"01-overview/01-intro.md": "## Intro\n\nHi\n",
			"01-overview/02-detail.md": "## Detail\n\nDetails\n",
		});
		const block = generateManifestBlock(rfcDir)!;
		// Directory aggregate row
		expect(block).toMatch(/\| 1 \| Overview \| sections\/01-overview\/ \|/);
		// Child rows
		expect(block).toMatch(/\| 1\.1 \| Intro \| sections\/01-overview\/01-intro\.md \|/);
		expect(block).toMatch(/\| 1\.2 \| Detail \| sections\/01-overview\/02-detail\.md \|/);
	});

	it("_intro.md is NOT listed as a separate row", () => {
		const rfcDir = makeRfc("demo", {
			"01-overview/_intro.md": "Overview intro text\n",
			"01-overview/01-detail.md": "## Detail\n\nFoo\n",
		});
		const block = generateManifestBlock(rfcDir)!;
		expect(block).not.toContain("_intro");
	});

	it("token count uses Math.ceil(bytes / 3.5) — not Math.floor", () => {
		// 4 bytes → Math.ceil(4/3.5) = Math.ceil(1.142...) = 2
		//          → Math.floor(4/3.5) = Math.floor(1.142...) = 1  ← distinguishes ceil vs floor
		const rfcDir = makeRfc("demo", { "01-summary.md": "ABCD" }); // exactly 4 bytes
		const block = generateManifestBlock(rfcDir)!;
		expect(block).toContain("| 1 | Summary | sections/01-summary.md | 2 |");
	});

	it("slugToTitle: converts kebab-slug to sentence-case", () => {
		const rfcDir = makeRfc("demo", { "01-full-layout.md": "x" });
		const block = generateManifestBlock(rfcDir)!;
		expect(block).toContain("| 1 | Full layout |");
	});

	it("sections appear in ascending numeric order", () => {
		const rfcDir = makeRfc("demo", {
			"03-design.md": "design",
			"01-summary.md": "summary",
			"02-motivation.md": "motivation",
		});
		const block = generateManifestBlock(rfcDir)!;
		const lines = block.split("\n");
		const nums = lines
			.filter((l) => l.startsWith("| ") && !l.startsWith("| §"))
			.map((l) => parseInt(l.split("|")[1].trim()));
		expect(nums).toEqual([1, 2, 3]);
	});
});

// ---------------------------------------------------------------------------
// extractManifestBlock unit tests
// ---------------------------------------------------------------------------

describe("extractManifestBlock", () => {
	it("returns null when markers are absent", () => {
		expect(extractManifestBlock("no markers here")).toBeNull();
	});

	it("returns the block including begin and end markers", () => {
		const content = "preamble\n<!-- rfc:manifest:begin — generated by `rfc index`; do not hand-edit -->\n| § | Title | File | Tokens |\ntable row\n<!-- rfc:manifest:end -->\npostamble";
		const block = extractManifestBlock(content)!;
		expect(block).toMatch(/^<!-- rfc:manifest:begin/);
		expect(block).toMatch(/<!-- rfc:manifest:end -->$/);
		expect(block).toContain("table row");
		expect(block).not.toContain("preamble");
		expect(block).not.toContain("postamble");
	});
});

// ---------------------------------------------------------------------------
// writeManifest unit tests
// ---------------------------------------------------------------------------

describe("writeManifest", () => {
	it("replaces existing markers in rfc.md", () => {
		const rfcDir = makeRfc("demo", { "01-summary.md": "## 1. Summary\n\nHello\n" });
		writeManifest(rfcDir);
		const content = readFileSync(path.join(rfcDir, "rfc.md"), "utf8");
		expect(content).toContain("| 1 | Summary |");
	});

	it("appends markers when they are absent", () => {
		const rfcDir = makeRfc("demo", { "01-summary.md": "## 1. Summary\n\nHello\n" });
		// Strip markers from rfc.md
		const rfcMdPath = path.join(rfcDir, "rfc.md");
		const content = readFileSync(rfcMdPath, "utf8");
		const stripped = content
			.replace(/<!-- rfc:manifest:begin[\s\S]*?<!-- rfc:manifest:end -->/g, "")
			.trimEnd() + "\n";
		writeFileSync(rfcMdPath, stripped);
		expect(readFileSync(rfcMdPath, "utf8")).not.toContain("rfc:manifest");

		writeManifest(rfcDir);
		const updated = readFileSync(rfcMdPath, "utf8");
		expect(updated).toContain("<!-- rfc:manifest:begin");
		expect(updated).toContain("<!-- rfc:manifest:end -->");
		expect(updated).toContain("| 1 | Summary |");
	});
});

// ---------------------------------------------------------------------------
// rfc index CLI command
// ---------------------------------------------------------------------------

describe("rfc index", () => {
	it("exits 2 when dir arg is missing", () => {
		const r = run(["index"]);
		expect(r.code).toBe(2);
	});

	it("exits 1 when rfc.md is missing", () => {
		const dir = mkdtempSync(path.join(tmpdir(), "gw-rfc-idx-"));
		try {
			const r = run(["index", dir]);
			expect(r.code).toBe(1);
		} finally {
			rmSync(dir, { recursive: true, force: true });
		}
	});

	it("exits 1 when sections/ is missing", () => {
		const rfcDir = createRfc("no-sections");
		rmSync(path.join(rfcDir, "sections"), { recursive: true, force: true });
		const r = run(["index", rfcDir]);
		expect(r.code).toBe(1);
	});

	it("exits 0 and writes the manifest", () => {
		const rfcDir = createRfc("demo");
		// Corrupt the manifest to make it stale
		const rfcMdPath = path.join(rfcDir, "rfc.md");
		const content = readFileSync(rfcMdPath, "utf8");
		const corrupted = content.replace(/<!-- rfc:manifest:end -->/, "<!-- corrupted -->\n<!-- rfc:manifest:end -->");
		writeFileSync(rfcMdPath, corrupted);

		const r = run(["index", rfcDir]);
		expect(r.code).toBe(0);
		expect(r.stdout).toContain("Manifest written");

		// Validate should now pass
		const v = run(["validate", rfcDir]);
		expect(v.code).toBe(0);
	});

	it("lists all section files reachable from the manifest", () => {
		const rfcDir = createRfc("full");
		const content = readFileSync(path.join(rfcDir, "rfc.md"), "utf8");
		// After rfc new, there should be 12 section rows
		const rows = content.split("\n").filter((l) => /^\| \d/.test(l));
		expect(rows.length).toBeGreaterThanOrEqual(12);
		// Each section file path should actually exist
		for (const row of rows) {
			const parts = row.split("|").map((s) => s.trim());
			const filePath = parts[3]; // 4th column
			if (!filePath || !filePath.startsWith("sections/")) continue;
			if (filePath.endsWith("/")) continue; // directory row — skip
			const abs = path.join(rfcDir, filePath);
			expect(existsSync(abs)).toBe(true);
		}
	});
});

// ---------------------------------------------------------------------------
// rfc validate — manifest freshness enforcement
// ---------------------------------------------------------------------------

describe("rfc validate manifest freshness", () => {
	// Primary acceptance criterion: a stale manifest fails validate.
	it("exits 1 when manifest is stale (hand-corrupted row)", () => {
		const rfcDir = createRfc("stale-test");
		const rfcMdPath = path.join(rfcDir, "rfc.md");
		const content = readFileSync(rfcMdPath, "utf8");
		// Corrupt one row by changing a token count
		const corrupted = content.replace(/\| (\d+) \| (.*?) \| (.*?) \| (\d+) \|/, (_m, n, t, f, tok) =>
			`| ${n} | ${t} | ${f} | ${parseInt(tok) + 9999} |`
		);
		writeFileSync(rfcMdPath, corrupted);
		const r = run(["validate", rfcDir]);
		expect(r.code).toBe(1);
		expect(r.stderr).toContain("manifest: stale");
	});

	// rfc index then validate exits 0 (standard round-trip)
	it("exits 0 after rfc index regenerates the manifest", () => {
		const rfcDir = createRfc("round-trip");
		// Corrupt then regenerate
		const rfcMdPath = path.join(rfcDir, "rfc.md");
		const content = readFileSync(rfcMdPath, "utf8");
		writeFileSync(rfcMdPath, content.replace(/\| \d+ \|.*\n/, ""));
		run(["index", rfcDir]);
		const r = run(["validate", rfcDir]);
		expect(r.code).toBe(0);
	});

	// A new section file without regenerating fails (M-M03)
	it("exits 1 when a new section file is added without regenerating (M-M03)", () => {
		const rfcDir = createRfc("new-section");
		// Add a 13th section file
		const sectionsDir = path.join(rfcDir, "sections");
		writeFileSync(path.join(sectionsDir, "13-extra.md"), "## 13. Extra\n\nExtra content\n");
		// Now validate without re-running rfc index
		const r = run(["validate", rfcDir]);
		expect(r.code).toBe(1);
		expect(r.stderr).toContain("manifest: stale");
	});

	// A section file is removed without regenerating fails
	it("exits 1 when a section file is removed without regenerating", () => {
		const rfcDir = createRfc("removed-section");
		// Remove one section file to make the manifest stale
		const sectionsDir = path.join(rfcDir, "sections");
		// Remove the last section (12-resolution.md) — leaves a numbering gap which is
		// also caught by layout validation, but manifest check runs too.
		rmSync(path.join(sectionsDir, "12-resolution.md"), { force: true });
		const r = run(["validate", rfcDir]);
		expect(r.code).toBe(1);
	});

	// schema: 1 RFC — manifest check must NOT run (M-M04)
	it("does not check manifest freshness for schema: 1 RFCs (M-M04)", () => {
		const rfcDir = createRfc("legacy");
		const rfcMdPath = path.join(rfcDir, "rfc.md");
		const content = readFileSync(rfcMdPath, "utf8");
		// Downgrade to schema: 1 and remove sections/ (schema 1 is lenient)
		const patched = content.replace(/^schema: 2$/m, "schema: 1");
		writeFileSync(rfcMdPath, patched);
		rmSync(path.join(rfcDir, "sections"), { recursive: true, force: true });
		const r = run(["validate", rfcDir]);
		expect(r.code).toBe(0);
	});

	// M-M01: equality boundary — a single extra space causes stale
	it("detects staleness on any byte difference — equality is strict (M-M01)", () => {
		const rfcDir = createRfc("equality-boundary");
		const rfcMdPath = path.join(rfcDir, "rfc.md");
		const content = readFileSync(rfcMdPath, "utf8");
		// Add a trailing space to one row (invisible but changes the block)
		const withSpace = content.replace(/\| 1 \|/, "| 1  |");
		writeFileSync(rfcMdPath, withSpace);
		const r = run(["validate", rfcDir]);
		expect(r.code).toBe(1);
		expect(r.stderr).toContain("manifest: stale");
	});

	// M-M02: changing only the token count triggers failure
	it("detects staleness when only a token count changes (M-M02)", () => {
		const rfcDir = createRfc("token-count-change");
		const rfcMdPath = path.join(rfcDir, "rfc.md");
		const content = readFileSync(rfcMdPath, "utf8");
		// Find a token count (digit at end of a manifest row) and change it by 1
		const changed = content.replace(/(\| sections\/\S+ \| )(\d+)( \|)/, (_m, pre, tok, post) =>
			`${pre}${parseInt(tok) + 1}${post}`
		);
		expect(changed).not.toBe(content); // Ensure we actually changed something
		writeFileSync(rfcMdPath, changed);
		const r = run(["validate", rfcDir]);
		expect(r.code).toBe(1);
		expect(r.stderr).toContain("manifest: stale");
	});
});

// ---------------------------------------------------------------------------
// rfc new — scaffolds manifest automatically
// ---------------------------------------------------------------------------

describe("rfc new manifest scaffold", () => {
	it("rfc new produces a rfc.md with a non-empty manifest block", () => {
		const rfcDir = createRfc("scaffold-demo");
		const content = readFileSync(path.join(rfcDir, "rfc.md"), "utf8");
		const block = extractManifestBlock(content);
		expect(block).not.toBeNull();
		// Should have at least one data row (§§1-12)
		expect(block!.split("\n").filter((l) => /^\| \d/.test(l)).length).toBeGreaterThanOrEqual(12);
	});

	it("rfc validate exits 0 immediately after rfc new (manifest is fresh)", () => {
		const rfcDir = createRfc("immediate-validate");
		const r = run(["validate", rfcDir]);
		expect(r.code).toBe(0);
	});
});

// ---------------------------------------------------------------------------
// Correctness: _intro.md exclusion — two separate code paths (M4, M8)
// ---------------------------------------------------------------------------

describe("_intro.md exclusion from manifest — correctness", () => {
	it("top-level sections/_intro.md is NOT included as a manifest row (M4)", () => {
		// _intro.md placed directly inside sections/ — exercises the top-level loop guard
		// at ~line 439. If the guard is mutated (e.g. condition negated), 01-summary.md
		// would be skipped instead, producing zero data rows.
		const rfcDir = makeRfc("intro-top-level", {
			"_intro.md": "Top-level intro stub.\n",
			"01-summary.md": "## Summary\n\nContent here.\n",
		});
		const block = generateManifestBlock(rfcDir)!;
		expect(block).not.toContain("_intro");
		// Exactly one data row — §1 for 01-summary.md only
		const dataRows = block.split("\n").filter((l) => /^\| \d/.test(l));
		expect(dataRows).toHaveLength(1);
		expect(dataRows[0]).toMatch(/^\| 1 \|/);
	});

	it("child-level sections/NN-dir/_intro.md is NOT included as a child row (M8)", () => {
		// _intro.md inside a numbered subdirectory — exercises the child loop guard
		// at ~line 464. If mutated, the manifest would gain a bogus child row for _intro.md.
		const rfcDir = makeRfc("intro-child-level", {
			"01-overview/_intro.md": "Overview intro stub.\n",
			"01-overview/01-detail.md": "## Detail\n\nContent here.\n",
			"01-overview/02-more.md": "## More\n\nExtra content.\n",
		});
		const block = generateManifestBlock(rfcDir)!;
		expect(block).not.toContain("_intro");
		// Exactly three data rows: §1 (dir aggregate), §1.1, §1.2 — NOT four
		const dataRows = block.split("\n").filter((l) => /^\| \d/.test(l));
		expect(dataRows).toHaveLength(3);
		expect(dataRows[0]).toMatch(/^\| 1 \|.*sections\/01-overview\//);
		expect(dataRows[1]).toMatch(/^\| 1\.1 \|/);
		expect(dataRows[2]).toMatch(/^\| 1\.2 \|/);
	});
});

// ---------------------------------------------------------------------------
// Correctness: manifest ordering — ascending (M6 top-level, M7 child)
// ---------------------------------------------------------------------------

describe("manifest section ordering — correctness", () => {
	it("top-level directory sections appear §1 before §2 before §3 (M6)", () => {
		// Uses directory sections so the sort at ~line 448 is exercised.
		// If reversed, §3 would appear first; indexOf comparisons catch it.
		const rfcDir = makeRfc("order-top-level", {
			"03-conclusion/01-final.md": "## Final\n\nConclusion.\n",
			"01-overview/01-intro.md": "## Intro\n\nOverview.\n",
			"02-analysis/01-detail.md": "## Detail\n\nAnalysis.\n",
		});
		const block = generateManifestBlock(rfcDir)!;
		const idx1 = block.indexOf("| 1 |");
		const idx2 = block.indexOf("| 2 |");
		const idx3 = block.indexOf("| 3 |");
		expect(idx1).toBeGreaterThanOrEqual(0);
		expect(idx2).toBeGreaterThanOrEqual(0);
		expect(idx3).toBeGreaterThanOrEqual(0);
		expect(idx1).toBeLessThan(idx2);
		expect(idx2).toBeLessThan(idx3);
	});

	it("child file rows within a directory appear §N.1 before §N.2 before §N.3 (M7)", () => {
		// Uses a directory with multiple children so the child sort at ~line 470 is exercised.
		// If reversed, §1.3 would appear first; indexOf comparisons catch it.
		const rfcDir = makeRfc("order-child-level", {
			"01-overview/03-third.md": "## Third\n\nThird child.\n",
			"01-overview/01-first.md": "## First\n\nFirst child.\n",
			"01-overview/02-second.md": "## Second\n\nSecond child.\n",
		});
		const block = generateManifestBlock(rfcDir)!;
		const idx11 = block.indexOf("| 1.1 |");
		const idx12 = block.indexOf("| 1.2 |");
		const idx13 = block.indexOf("| 1.3 |");
		expect(idx11).toBeGreaterThanOrEqual(0);
		expect(idx12).toBeGreaterThanOrEqual(0);
		expect(idx13).toBeGreaterThanOrEqual(0);
		expect(idx11).toBeLessThan(idx12);
		expect(idx12).toBeLessThan(idx13);
	});
});

// ---------------------------------------------------------------------------
// Digest invariance: manifest does NOT affect computeBodyDigest
// ---------------------------------------------------------------------------

describe("body_digest invariance", () => {
	it("computeBodyDigest returns the same value before and after writing the manifest", async () => {
		const { computeBodyDigest, parseFrontmatter, generateManifestBlock, writeManifest } =
			await import("../../hooks/lib/rfc-io.mjs");

		const rfcDir = createRfc("digest-invariance");
		const content1 = readFileSync(path.join(rfcDir, "rfc.md"), "utf8");
		const { frontmatter: fm1 } = parseFrontmatter(content1);
		const digest1 = computeBodyDigest(fm1, rfcDir);

		// Corrupt manifest and then regenerate — digest must not change
		const rfcMdPath = path.join(rfcDir, "rfc.md");
		writeFileSync(rfcMdPath, content1.replace(/<!-- rfc:manifest:end -->/, "<!-- rfc:manifest:end -->\nEXTRA LINE"));
		writeManifest(rfcDir);

		const content2 = readFileSync(rfcMdPath, "utf8");
		const { frontmatter: fm2 } = parseFrontmatter(content2);
		const digest2 = computeBodyDigest(fm2, rfcDir);

		expect(digest1).toBe(digest2);
	});
});
